export default `<?xml version="1.0"?>
<!DOCTYPE article PUBLIC "ExampleArticle 1.0" "http://substance.io/ExampleArticle-1.0.dtd">
<example-article>
  <title>Sample title</title>
  <body>
    <paragraph>JEFF NICHOLS SAT in the dark, listening. It was 2015, just after New Year’s, and the writer-director was completing a mix inside a cavernous dubbing stage on the Warner Bros. lot in Burbank, California. Nichols and his team were in the process of weaving hundreds of tracks of dialog, music, and sound effects to create the aural backdrop for his fourth film, a sci-fi thriller called <i>Midnight Special</i>. An explosion was “too wonky,” the music “a little too hot.” Moviegoers can only truly register so many elements at once, Nichols said. “You don’t want to highlight the way it’s put together. You want it to be experiential. <i>Moving</i>.”</paragraph>
    <paragraph>If you had to choose two adjectives to describe Nichols’ earlier three films, you could do worse than <i>experiential</i> and <i>moving</i>. His debut, 2007’s <i>Shotgun Stories</i>, was a revenge story filled with foreboding. His next film, 2011’s <i>Take Shelter</i>, was a paranoid, apocalyptic tale that explored what a man will do to protect the ones he loves. Then came <i>Mud</i>, in 2012, a coming-of-age story built around two boys’ discovery of a fugitive (Matthew McConaughey) living on an island in the middle of the Mississippi River.</paragraph>
    <paragraph>All three films had been acclaimed but, as Nichols acknowledged, “underseen.” He had resolved not to let this happen again, which is why he was here, in this tricked-out dubbing stage—the same one, the Arkansas native delighted in pointing out, where another one-time indie darling, Christopher Nolan, had mixed his 2014 blockbuster <i>Interstellar</i>. If Nichols had anything to say about it, <i>Midnight Special</i>would do better than any of his other movies and be a stepping-stone to something even bigger. To <i>experiential</i> and <i>moving</i>, Nichols wanted to add <i>blockbusting</i>.</paragraph>
    <paragraph>A few more tweaks and Nichols announced it was time for a break. Blinking as we stepped into the bright LA sunshine, we headed for the studio’s commissary. We took our burgers to a picnic table outside, and as soon as we sat down, Nichols’ usually voluble Little Rock twang dropped to a whisper. “Wow!” he hissed, his eyes locked on a gray-haired, lanky guy about 100 feet away. “There’s Clint Eastwood! Right there!” I looked, and, yep, there he was.</paragraph>
    <paragraph>“Oh, man, that’s rad,” Nichols said, giddy as any fan. “I’ve eaten here, like, a million times, and I’ve never seen anyone famous.”</paragraph>
    <pullquote>
      <pullquote-body>
        <paragraph>The path from Southern Gothic indies to superheroes isn’t an obvious one—and not one that everybody with the film-school cred of Nichols would want to walk.</paragraph>
      </pullquote-body>
      <pullquote-credit>
        <paragraph>credit</paragraph>
      </pullquote-credit>
    </pullquote>
    <paragraph>This felt like more than a star sighting. At 85, Eastwood is a movie icon and Warner Bros.’ longest-reigning auteur, having made 37 films there over 45 years. His no-­nonsense directing style is something that Nichols consciously emulates. It was hard not to see Dirty Harry’s walk-on cameo as some sort of an omen. “Nobody effs with Clint Eastwood!” Nichols said. “Anywhere, much less here.”</paragraph>
    <paragraph>He took another bite of hamburger as we talked directors. “There’s a short roster of people who can step in and direct these $100 million and $200 million films,” Nichols said.</paragraph>
    <paragraph>Did he want to be on that short list? “If it’s good, and if I’m given enough rope to hang myself, totally!”</paragraph>
    <paragraph>Little by little, strategic decision by strategic decision, Nichols has been preparing to make not <i>this</i> movie so much as the <i>next</i> one or perhaps the one after that. At a distinctly unwhopping $23 million, <i>Midnight Special</i>’s budget is more than twice as big as those of his first three movies combined. This film is about a boy with extraordinary powers on the run across the South with his dad, with special effects and car chases and a real live marketing budget from a real live movie studio—Warner Bros., a place where auteur directors, from Eastwood to Nolan, take on giant projects.</paragraph>
    <paragraph>The path from Southern Gothic indies to superheroes isn’t an obvious one, though—and not one that everybody with the film-school cred of Nichols would want to walk. But he does, even if the things that make Nichols a great director might mean he won’t get the chance.</paragraph>
    <paragraph>Don’t worry, though. Jeff Nichols has a plan.</paragraph>
    <figure image-source="https://www.wired.com/wp-content/uploads/2016/02/jeffnichols11.jpg" position="full-bleed">
      <title>Figure 1</title>
      <caption><paragraph>“There’s one right place to put the camera,” <i>Nichols</i> says. “I’m a big believer in that.”</paragraph></caption>
    </figure>
    <paragraph>Nichols wrote the script for his first movie, <i>Shotgun Stories</i>, with an actor in mind: Michael Shannon. They’d never met, but after seeing Shannon in <a href="https://youtu.be/0ShWGyC408I"><i>8 Mile</i></a> and <i>High Crimes</i>, Nichols decided he wanted him in every movie he would ever make. Through a former professor, Nichols—then just 24—tracked Shannon down and persuaded him to read the script. “Your agent’s always telling you, don’t work with first-time directors, work with somebody who knows what they’re doing,” Shannon told me. “But I got the impression from Jeff the first time I talked to him that he knew what he was doing.”</paragraph>
    <paragraph>That’s because Nichols has been thinking about movies for a long time. His dad and uncle own a furniture store in Little Rock. But during off-hours, when most dads might take their sons fishing, Nichols’ dad would take Jeff to the multiplex. Nichols loved John Carpenter, Steven Spielberg, John Sayles, Ridley Scott, and “anything with Paul Newman in it.” He read a lot too—S. E. Hinton, the master of young-adult fiction, made a huge impression, especially with <i>The Outsiders</i> and <i>Rumble Fish</i>. (Motorcycle Boy has “the best name ever,” Nichols said.)</paragraph>
    <paragraph>Nichols studied filmmaking at the University of North Carolina School of the Arts, which he describes as more like a trade school in that it stresses skills over theory. Before Nichols wrote his first screenplay, he told his father that it would be about New York mobsters. Gently, his dad suggested that, instead, he write about “a place you know that others don’t.” The result was <i>Shotgun Stories</i>, set amid the cotton fields and back roads of southeastern Arkansas.</paragraph>
  </body>
</example-article>`
